$engine: 3
$minFxVersion: 5104
$onesync: on
name: overextended_recipe
version: 0.2.2
author: DokaDoka
description: Overextended Server Recipe

tasks:
  ## default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  ## prepare server.cfg, database and icon
  - action: download_github
    src: https://github.com/overextended/ox_recipes
    ref: ox
    dest: ./tmp/ox

  - action: move_path
    src: ./tmp/ox/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/ox/oxpog.png
    dest: ./oxpog.png

  ## ox_core and modules
  - action: download_file
    url: https://github.com/overextended/ox_core/releases/latest/download/ox_core.zip
    path: ./tmp/ox_core.zip
  - action: unzip
    src: ./tmp/ox_core.zip
    dest: ./resources/[ox]

  - action: connect_database
  - action: query_database
    file: ./resources/[ox]/ox_core/database.sql

  - action: download_github
    src: https://github.com/overextended/ox_groups
    ref: main
    dest: ./resources/[ox]/ox_groups

  - action: download_github
    src: https://github.com/overextended/ox_accounts
    ref: main
    dest: ./resources/[ox]/ox_accounts

  ## oxmysql
  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/oxmysql.zip
  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources/[ox]

  ## fivem-appearance
  - action: download_file
    url: https://github.com/overextended/fivem-appearance/releases/latest/download/fivem-appearance.zip
    path: ./tmp/fivem-appearance.zip
  - action: unzip
    src: ./tmp/fivem-appearance.zip
    dest: ./resources/[ox]

  ## ox_inventory
  - action: download_file
    url: https://github.com/overextended/ox_inventory/releases/latest/download/ox_inventory.zip
    path: ./tmp/ox_inventory.zip
  - action: unzip
    src: ./tmp/ox_inventory.zip
    dest: ./resources/[ox]
    
  ## ox_lib
  - action: download_github
    src: https://github.com/overextended/ox_lib
    ref: master
    dest: ./resources/[ox]/ox_lib

  ## ox_fuel
  - action: download_github
    src: https://github.com/overextended/ox_fuel
    ref: main
    dest: ./resources/[ox]/ox_fuel

  ## ox_vehicles
  - action: download_github
    src: https://github.com/overextended/ox_vehicles
    ref: main
    dest: ./resources/[ox]/ox_vehicles

  ## pe-ui
  - action: download_github
    src: https://github.com/project-error/pe-ui
    ref: master
    dest: ./resources/[pe]/pe-ui

  - action: replace_string
    file: ./resources/[pe]/pe-ui/config.json
    search: '"targetFramework": "qb-core"'
    replace: '"targetFramework": "ox"'

  ## npwd
  - action: download_file
    url: https://github.com/project-error/npwd/releases/latest/download/npwd.zip
    path: ./tmp/npwd.zip
  - action: unzip
    src: ./tmp/npwd.zip
    dest: ./resources/[pe]

  - action: query_database
    file: ./resources/[pe]/npwd/import.sql

  - action: replace_string
    file: ./resources/[pe]/npwd/config.json
    search: '"level": "silly"'
    replace: '"level": "error"'

  ## pma-voice
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/pma-voice

  ## screenshot-basic
  - action: download_github
    src: https://github.com/project-error/screenshot-basic
    ref: master
    dest: ./resources/[pe]/screenshot-basic

  ## loadingscreen
  - action: download_github
    src: https://github.com/DokaDoka/pe-basicloading
    ref: ox
    dest: ./resources/[pe]/pe-basicloading

  - action: replace_string
    mode: all_vars
    file:
    - ./resources/[pe]/pe-basicloading/web/config.js

  ## cleanup
  - action: remove_path
    path: ./tmp
